// ─── Export specifications for all catalog items ─────────────────────────────
// These provide the full technical context for Claude Code to consume.

// Base URL for specs served from public/specs/ on Vercel
const SPEC_BASE = "https://github.com/Raiz-Educacao-SA/design-library/blob/main/public/specs";

export interface SolutionExportSpec {
  id: string;
  name: string;
  category: string;
  complexity: string;
  description: string;
  tags: string[];
  source: string;
  sourceRepo: string;
  specUrl: string;
  specRaw: string;
  keyFiles: string[];
  dependencies: string[];
  stackUsed: string[];
}

export const SOLUTION_SPECS: Record<string, Omit<SolutionExportSpec, "id" | "name" | "category" | "complexity" | "description" | "tags">> = {
  "dashboard-kpi": { source: "salarios-platform", sourceRepo: "Raiz-Educacao-SA/fgts-platform", specUrl: `${SPEC_BASE}/01-dashboard-kpi.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/01-dashboard-kpi.md`, keyFiles: ["src/components/ui/kpi-card.tsx", "src/components/charts/sparkline.tsx"], dependencies: ["lucide-react", "recharts"], stackUsed: ["Next.js 16", "Tailwind 4", "shadcn/ui"] },
  "table-filters-export": { source: "salarios-platform + auditoria-raiz", sourceRepo: "Raiz-Educacao-SA/fgts-platform", specUrl: `${SPEC_BASE}/02-table-filters-export.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/02-table-filters-export.md`, keyFiles: ["src/components/funcionarios/funcionarios-table.tsx", "src/components/dashboard/global-filters.tsx", "src/components/ui/export-button.tsx"], dependencies: ["ExcelJS", "useSearchParams"], stackUsed: ["Next.js 16", "Tailwind 4", "shadcn/ui"] },
  "forms-multistep": { source: "ticket-raiz", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/03-forms-multistep.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/03-forms-multistep.md`, keyFiles: ["src/lib/bpms/forms/form-engine.ts", "src/components/bpms/forms/dynamic-form.tsx"], dependencies: ["react-hook-form", "zod", "@hookform/resolvers"], stackUsed: ["Next.js 16", "React Hook Form", "Zod"] },
  "status-workflow-timeline": { source: "auditoria-raiz", sourceRepo: "Raiz-Educacao-SA/escola-legal", specUrl: `${SPEC_BASE}/04-status-workflow-timeline.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/04-status-workflow-timeline.md`, keyFiles: ["src/components/solicitacoes/WorkflowActions.tsx", "src/components/solicitacoes/StatusBadge.tsx"], dependencies: ["shadcn/ui Dialog", "sonner", "lucide-react"], stackUsed: ["Next.js 16", "Tailwind 4", "shadcn/ui"] },
  "app-shell-sidebar": { source: "sophia-educacional-frontend", sourceRepo: "Raiz-Educacao-SA/sophia-raiz", specUrl: `${SPEC_BASE}/05-app-shell-sidebar.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/05-app-shell-sidebar.md`, keyFiles: ["src/components/layout/app-shell.tsx", "src/components/layout/sidebar.tsx", "src/components/layout/topbar.tsx"], dependencies: ["next/navigation", "next-themes", "lucide-react"], stackUsed: ["Next.js 16", "Tailwind 4", "shadcn/ui"] },
  "workflow-builder": { source: "ticket-raiz", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/06-workflow-builder.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/06-workflow-builder.md`, keyFiles: ["src/components/bpms/designer/process-designer.tsx", "src/components/bpms/designer/nodes/"], dependencies: ["@xyflow/react", "react-flow"], stackUsed: ["Next.js 16", "React Flow", "Tailwind 4"] },
  "chat-ai-streaming": { source: "automata", sourceRepo: "Raiz-Educacao-SA/automata-raiz", specUrl: `${SPEC_BASE}/07-chat-ai-streaming.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/07-chat-ai-streaming.md`, keyFiles: ["components/chat/chat-panel.tsx", "components/chat/chat-messages.tsx", "app/api/chat/route.ts"], dependencies: ["ai", "@ai-sdk/react", "DefaultChatTransport"], stackUsed: ["Next.js 16", "AI SDK v6", "Tailwind 4"] },
  "pageflip-3d": { source: "fliphtml-raiz", sourceRepo: "Raiz-Educacao-SA/fliphtml-raiz", specUrl: `${SPEC_BASE}/08-pageflip-3d.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/08-pageflip-3d.md`, keyFiles: ["src/components/flipbook/flipbook-viewer.tsx"], dependencies: ["page-flip (dynamic import)"], stackUsed: ["Next.js 16", "page-flip", "Tailwind 4"] },
  "qr-designer": { source: "qrcode-facil-replica", sourceRepo: "Raiz-Educacao-SA/qrcode-raiz", specUrl: `${SPEC_BASE}/09-qr-designer.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/09-qr-designer.md`, keyFiles: ["src/components/qr-generator/index.tsx", "src/components/qr-generator/style-editor.tsx", "src/components/qr-generator/qr-preview.tsx"], dependencies: ["qr-code-styling"], stackUsed: ["Next.js 16", "Tailwind 4", "shadcn/ui"] },
  "code-editor": { source: "raiz-platform", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/10-code-editor.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/10-code-editor.md`, keyFiles: ["src/components/chat/canvas/MonacoCanvas.tsx"], dependencies: ["@monaco-editor/react (dynamic)"], stackUsed: ["Next.js 14", "Monaco Editor", "Tailwind 3"] },
  "dragdrop-virtual-scroll": { source: "raiz-agent-dashboard", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/11-dragdrop-virtual-scroll.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/11-dragdrop-virtual-scroll.md`, keyFiles: ["src/components/kanban/KanbanBoard.tsx", "src/components/agents/AgentTimeline.tsx"], dependencies: ["@dnd-kit/core", "@tanstack/react-virtual", "zustand"], stackUsed: ["Next.js 14", "dnd-kit", "TanStack Virtual"] },
  "document-generation": { source: "raiz-docs", sourceRepo: "Raiz-Educacao-SA/raiz-docs", specUrl: `${SPEC_BASE}/12-document-generation.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/12-document-generation.md`, keyFiles: ["src/lib/export/export-pdf.ts", "src/lib/export/export-docx.ts", "src/lib/export/export-xlsx.ts", "src/lib/export/common.ts"], dependencies: ["jspdf", "docx", "xlsx", "file-saver"], stackUsed: ["Next.js 16", "jsPDF", "SheetJS"] },
  "rag-knowledge-base": { source: "raiz-platform", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/13-rag-knowledge-base.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/13-rag-knowledge-base.md`, keyFiles: ["src/components/rag/RagPanel.tsx", "src/components/rag/DocumentList.tsx", "src/components/rag/DocumentUpload.tsx"], dependencies: ["Supabase", "polling"], stackUsed: ["Next.js 14", "Supabase", "Tailwind 3"] },
  "social-media-publisher": { source: "raiz-platform", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/14-social-media-publisher.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/14-social-media-publisher.md`, keyFiles: ["src/components/social-media/publishing/PostComposer.tsx", "src/components/social-media/publishing/ContentCalendar.tsx"], dependencies: ["date-fns", "shadcn/ui"], stackUsed: ["Next.js 14", "Tailwind 3", "date-fns"] },
  "bi-data-explorer": { source: "raiz-platform", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/15-bi-data-explorer.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/15-bi-data-explorer.md`, keyFiles: ["src/components/bi/GraphicWalkerExplorer.tsx", "src/components/bi/GraphicWalkerWrapper.tsx"], dependencies: ["@kanaries/graphic-walker (dynamic)"], stackUsed: ["Next.js 14", "Graphic Walker", "Tailwind 3"] },
  "meeting-transcript-ai": { source: "raiz-platform", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/16-meeting-transcript-ai.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/16-meeting-transcript-ai.md`, keyFiles: ["src/components/meet/TranscriptTimeline.tsx", "src/components/meet/SummaryPanel.tsx", "src/components/meet/AudioWaveform.tsx"], dependencies: ["AI transcription service"], stackUsed: ["Next.js 14", "Tailwind 3", "shadcn/ui"] },
  "contract-lifecycle": { source: "raiz-platform", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/17-contract-lifecycle.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/17-contract-lifecycle.md`, keyFiles: ["src/components/clm/ai/RiskAnalysisView.tsx", "src/components/clm/contracts/ContractNegotiationPanel.tsx"], dependencies: ["AI risk analysis", "SVG"], stackUsed: ["Next.js 14", "Tailwind 3", "shadcn/ui"] },
  "content-studio-ai": { source: "raiz-platform", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/18-content-studio-ai.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/18-content-studio-ai.md`, keyFiles: ["src/components/content-studio/TiptapEditor.tsx", "src/components/content-studio/presentation/editor/SlideCanvas.tsx"], dependencies: ["@tiptap/react", "Canvas API"], stackUsed: ["Next.js 14", "Tiptap", "Tailwind 3"] },
  "litigation-case-manager": { source: "raiz-platform", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/19-litigation-case-manager.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/19-litigation-case-manager.md`, keyFiles: ["src/components/contencioso/settings/", "src/app/(auth)/contencioso/"], dependencies: ["AI copilot"], stackUsed: ["Next.js 14", "Tailwind 3", "shadcn/ui"] },
  "data-catalog-governance": { source: "raiz-platform", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/20-data-catalog-governance.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/20-data-catalog-governance.md`, keyFiles: ["src/components/totvs-sql/api-factory/ApiFactoryDashboard.tsx", "src/components/data-explorer/DataExplorer.tsx"], dependencies: ["TOTVS SQL engine"], stackUsed: ["Next.js 14", "Tailwind 3", "shadcn/ui"] },
  "ai-app-builder": { source: "raiz-platform", sourceRepo: "Raiz-Educacao-SA/rAIz_Cowork", specUrl: `${SPEC_BASE}/21-ai-app-builder.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/21-ai-app-builder.md`, keyFiles: ["src/components/vibecoding/VibeCodingExecutionView.tsx", "src/components/vibecoding/VibeCodingWizard.tsx", "src/components/vibecoding/EmbeddedApp.tsx"], dependencies: ["AI build pipeline", "iframe"], stackUsed: ["Next.js 14", "Tailwind 3"] },
  "tv-realtime-counter": { source: "cmef-contador-matriculas", sourceRepo: "Raiz-Educacao-SA/cmef-contador-matriculas", specUrl: `${SPEC_BASE}/22-tv-realtime-counter.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/22-tv-realtime-counter.md`, keyFiles: ["contadorMatriculasNovo.html"], dependencies: ["Pure HTML/CSS/JS"], stackUsed: ["Vanilla HTML/CSS/JS"] },
  "skill-assessment-profiler": { source: "skillcert-raiz", sourceRepo: "Raiz-Educacao-SA/skillcert-raiz", specUrl: `${SPEC_BASE}/23-skill-assessment-profiler.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/23-skill-assessment-profiler.md`, keyFiles: ["components/IndividualView.tsx", "components/TeamView.tsx"], dependencies: ["Hand-built SVG", "Gemini AI"], stackUsed: ["React (Vite)", "Custom SVG"] },
  "contractor-management": { source: "sistema-gestao-pj-raiz", sourceRepo: "Raiz-Educacao-SA/sistema-gestao-pj-raiz", specUrl: `${SPEC_BASE}/24-contractor-management.md`, specRaw: `https://raw.githubusercontent.com/Raiz-Educacao-SA/design-library/main/public/specs/24-contractor-management.md`, keyFiles: ["src/components/PJRegistrationForm.tsx", "src/components/PaymentForm.tsx", "src/components/ImportModule.tsx"], dependencies: ["CNPJ validation"], stackUsed: ["React (Vite)", "Tailwind"] },
};
